import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container mx-auto flex h-screen flex-col bg-[#171717]">
        <header>
          <nav className="flex justify-between p-5 text-lg text-white">
            <div>Menu</div>
            <div>Logo</div>
            <div>Profile</div>
          </nav>
        </header>
        <main className="grow bg-white">{children}</main>
        <footer className="text-center text-white">
          Created by Kevin Tatooles
        </footer>
      </body>
    </html>
  );
}
